; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = 
	pre:pre_build_version_script.py
	post:post_build_script.py
board_build.cxx_std = 17
board_build.filesytem = littlefs
board_build.fs_dir = data
board_build.partitions = default_4MB.csv
build_flags = 
	-I src
build_src_filter = 
	+<*>
lib_deps = 
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	knolleary/PubSubClient@^2.8
	links2004/WebSockets@^2.6.1

[env:jc8048w550c]
platform = espressif32
board = JC8048W550C
framework = arduino
extra_scripts =
	pre:pre_build_version_script.py
	post:post_build_script.py
board_build.cxx_std = 17
board_build.filesystem = littlefs
board_build.fs_dir = data
build_flags =
	-I src
	-D X32_TARGET_HEAD_UNIT=1
	-D X32_SCREEN_EEZ_LVGL=1
build_src_filter =
	+<*>
	-<UI/>
	-<Controller/>
	-<Machine/Context/>
	-<State/A/>
	-<State/Scene.cpp>
	-<Service/ESPUpdate.cpp>
	-<Service/HServer.cpp>
	-<Service/MQTTc.cpp>
	-<Service/PinTester.cpp>
lib_deps =
lib_ignore =
	FastAccelStepper
	Nextion
	ESP32Encoder
